In [1]:
#importing numpy library file
import numpy as np

In [2]:
#creating a array
a = np.array([1,2,3])

In [3]:
#printing an array
a

array([1, 2, 3])

In [4]:
#acessing array through indexing
a[2]

3

In [5]:
#creating a multi-dimensional array
a = np.array([[1,2,3],[3,4,5],[6,7,8]])

In [7]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#function used to find the dimension of the array (ndim() function)
#a 2d array is a bunch of 1d array and a 3d array is the bunch of 2d arrays and so on...
a.ndim

2

In [9]:
#to change the data type of a element (dytpe parameter)
a = np.array([1,2,3] , dtype = "float64")

In [10]:
#function used to find the datatype of the array
a.dtype

dtype('float64')

In [11]:
a

array([1., 2., 3.])

In [16]:
#creatinga complexnumber datatype array
a = np.array([[1,2,3],[3,4,5],[6,7,8]],dtype=complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j],
       [6.+0.j, 7.+0.j, 8.+0.j]])

In [15]:
#size function returns the total number of elements in an array (size() function)
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
a.size

9

In [4]:
#shape functions returns the shape of the array (shape() function)
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
a.shape

(3, 3)

In [2]:
#for intialinzing array with all zeros (zeros() function)
import numpy as np
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#for intialinzing array with all ones (ones() function)
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
#to create array in a range (arange() function)
a =np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
#to create array in a range (arange() function) by step value
# in this exaple it skips every alternate values
a =np.arange(1,9,2)
a

array([1, 3, 5, 7])

In [37]:
#to reshape a array (reshape() function)
a = np.array([[1,2],[3,4],[6,7]])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 6, 7]])

In [38]:
#to flatten a array (ravel( ) function)
a.ravel()

array([1, 2, 3, 4, 6, 7])

In [40]:
#to automatically generate linearly sapaced array 
#it generates equally spaced 20 values between 1 to 10
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [42]:
#to find out minimum and maximum element in an array (min() and max() function)
print(a.min())
print(a.max())

1
7


In [45]:
#to find sum of element in an array (sum() function)
print(a.sum())
#to find the sum induvidual columns (axis = 0 parameter)
print(a.sum(axis = 0))
#to find the sum induvidual rows (axis = 1 parameter)
print(a.sum(axis = 1))

23
[10 13]
[ 3  7 13]


In [8]:
#to find the sqrt of each element (sqrt() function)
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [47]:
#to find the standard deviation of the array (std() function)
np.std(a)

2.1147629234082532

In [55]:
#array operations in numpy (this cant be performed in a python list)
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[9,9]])
print(a+b)
print(b-a)
print(a*b)
print(a/b)
#to perform matrix multiplication (dot() function)
print(a.dot(b))

[[ 7  4]
 [12 13]]
[[5 0]
 [6 5]]
[[ 6  4]
 [27 36]]
[[0.16666667 1.        ]
 [0.33333333 0.44444444]]
[[24 20]
 [54 42]]


In [2]:
#slicing a numpy array
import numpy as np
a = np.array([
    [1,2,3],
    [3,4,5],
    [6,7,8]
])

In [3]:
a[:,0]

array([1, 3, 6])

In [4]:
a[-1,:]

array([6, 7, 8])

In [6]:
a[:,:]#this copies the array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
a[:,1:3]

array([[2, 3],
       [4, 5],
       [7, 8]])

In [8]:
a[1:2,0:3]

array([[3, 4, 5]])

In [14]:
#iterating through an array
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
for i in a:
    print(i)

[1 2 3]
[3 4 5]
[6 7 8]


In [16]:
#to flatten an array (falt() function)
for i in a.flat:
    print(i)

1
2
3
3
4
5
6
7
8


In [22]:
#stacking an array
a=np.arange(6).reshape(3,2)#this creates a array of 3 rows and 2 columns containing numbers ranging from 0 to 5
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [27]:
np.hstack((a,b))#it stacks the arrays horizontally aka side by side (hstack() function)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [28]:
np.vstack((a,b))#it stacks the arrays vertically (vstack() function)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
#splitting an array
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
#it splits the array horizontally into 3 arrays (hsplit() function)
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [37]:
#it splits the array vertically into 2 arrays (vsplit() function)
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [38]:
#indexing through boolean array
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b = a>4# returns a boolean array by the given condition
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
a[b]#creating an array for true boolean values

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
a[b]=-1#replacing -1 in the place of true values
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

nditer function should also be studied :https://youtu.be/XawR6CjAYV4?si=J6IYkKBA5RlnM6Aw